/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2024-06-05 04:21:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ting.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ting.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 Member member = (Member) session.getAttribute("member");	
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"./css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/login_in.css\" rel=\"stylesheet\">\r\n");
      out.write("    <title>早午餐店</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>神風餐廳-brunch  </h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <nav>\r\n");
      out.write("        <a href=\"#\">首頁</a>\r\n");
      out.write("        <a href=\"activity.html\">特別活動</a>\r\n");
      out.write("        <a href=\"menu.html\">美味菜單</a>\r\n");
      out.write("        <a href=\"branchmap.html\">門市據點</a>\r\n");
      out.write("        <a href=\"feedback.html\">聯絡我們</a>\r\n");
      out.write("        <div class=\"ting-login-in\" id=\"ting-login-in\">\r\n");
      out.write("        \t<a href=\"./member.jsp\">\r\n");
      out.write("        \t\t");
 if(member != null)
        			 out.print(member.getMemberName());
      out.write("\r\n");
      out.write("        \t</a><span> 會員</span>\r\n");
      out.write("            <a href='./logout.jsp'>登出</a>    \r\n");
      out.write("\r\n");
      out.write("        </div>       \r\n");
      out.write("        <button class=\"btnLogin-popup\">登入 Login</button>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"menu-item\">\r\n");
      out.write("            <h2>霸氣早晨炫風早餐</h2>\r\n");
      out.write("            <p>新鮮蔬菜、火腿和起司，夾在酥脆的麵包中。</p>\r\n");
      out.write("            <p>價格：$5.99</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"menu-item\">\r\n");
      out.write("            <h2>咖啡火箭能量燃早</h2>\r\n");
      out.write("            <p>煎蛋、培根、香腸、烤土豆和吐司。</p>\r\n");
      out.write("            <p>價格：$8.99</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2023 神風早午餐店. All rights reserved.</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!--登入介面-->\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <span class=\"icon-close\">\r\n");
      out.write("            <ion-icon name=\"close\"></ion-icon>\r\n");
      out.write("        </span>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-box login\">\r\n");
      out.write("            <h2>Login登入</h2>\r\n");
      out.write("            <form id=\"login_Form\" action=\"/Breakfast/doLogin\"  method=\"post\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"mail-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"email\" required name=\"login_Email\" id=\"login_Email\">\r\n");
      out.write("                    <label>信箱Email</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"lock-closed-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"password\" required required name=\"login_Password\" id=\"login_Password\">\r\n");
      out.write("                    <label>密碼Password</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"remember-forget\">\r\n");
      out.write("                    <label ><input type=\"checkbox\">記住帳號</label>\r\n");
      out.write("                    <a href=\"#\">Forget Password?</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"btn\" onclick=\"checkLogin()\">登入 Login</button>              \r\n");
      out.write("                <div class=\"login-register\">\r\n");
      out.write("                    <p>申請帳號\r\n");
      out.write("                    <a \r\n");
      out.write("                    href=\"#\"\r\n");
      out.write("                    class=\"register-link\">Register</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-box register\">\r\n");
      out.write("            <h2>Registration註冊</h2>\r\n");
      out.write("            <form id=\"register_Form\" action=\"/Breakfast/doRegister\"  method=\"post\">\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"person-add-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"text\" required name=\"register_Username\" id=\"register_Username\">\r\n");
      out.write("                    <label>暱稱Username</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"mail-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"email\" required name=\"register_Email\" id=\"register_Email\">\r\n");
      out.write("                    <label>信箱Email</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <span class=\"icon\"><ion-icon name=\"lock-closed-outline\"></ion-icon></span>\r\n");
      out.write("                    <input type=\"password\" required name=\"register_Password\" id=\"register_Password\">\r\n");
      out.write("                    <label>密碼Password</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"remember-forget\">\r\n");
      out.write("                    <label ><input type=\"checkbox\">I agree to the terms & conditions</label>\r\n");
      out.write("                     \r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"btn\" onclick=\"checkRegister()\">註冊 Register</button>\r\n");
      out.write("                <div class=\"login-register\">\r\n");
      out.write("                    <p>已有帳號\r\n");
      out.write("                    <a \r\n");
      out.write("                    href=\"#\"\r\n");
      out.write("                    class=\"login-link\">Login</a>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./include/isRegisterSucceed.jsp", out, true);
      out.write("\r\n");
      out.write("    <script src=\"./js/email.js\"></script> \r\n");
      out.write("    <script type=\"module\" src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("    <script nomodule src=\"https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!--登入介面-->\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
